server:
  port: 6001 # 服务端口

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: false # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:    # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      # 注意，通过网页访问时没有 "/eureka" 路径，直接是: localhost:6001 就可以访问了。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

