server:
  port: 8000

eureka:
  instance:
    # 配置当前主机名
    hostname: localhost
  client:
    # 单机eureka 时需要为false
    register-with-eureka: false  # 指定当前主机是否需要向Eureka Server注册自己
    fetch-registry: false   # 指定当前主机是否需要从Eureka Server下载服务注册表
    service-url:
      # 当前Eureka Server对外暴露的服务地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # defaultZone: http://localhost:8000/eureka

  server:
    # 关闭自我保护机制
    enable-self-preservation: false
    # 指定自我保护机制的开启阈值，默认为 0.85
    renewal-percent-threshold: 0.75
    # 设置server端剔除不可用服务的时间窗，单位毫秒
    eviction-interval-timer-in-ms: 4000
