server:
  port: 8081

spring:
  # 配置spring data jpa
  jpa:
    # 指定是否在spring容器启动时创建表，默认false
    generate-ddl: true
    # 指定在控制台是否显示SQL语句，默认false
    show-sql: true
    # 指定应用重启后不重新更新表内容
    hibernate:
      ddl-auto: none
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://docker:3306/suyh_db?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root

  # 指定当前微服务名称
  application:
    name: abcmsc-provider-depart

# 配置日志
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger:%L - %msg%n'

  level:
    root: info
    org.hibernate: info
    # 在${spring.jpa.show-sql}为true时显示SQL中的动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 在${spring.jpa.show-sql}为true时显示查询结果
    org.hibernate.hql.internal.ast.exec.BasicExecutor: trace
    com.suyh12101: debug

eureka:
  client:
    service-url:
      # 相同的配置项 eureka.client.service-url.defaultZone 在服务端是指定暴露给客户端访问的地址
      # 而它在客户端，则是访问eureka 服务的地址
      # 指定当前Client所要连接的eureka Server
      defaultZone: http://localhost:8000/eureka
      # defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka,http://localhost:8300/eureka
  instance:
    # 该ID 将会显示在eureka 注册中心的Status 那一栏
    # 但是如果同一微服务的这个ID 相同，则eureka server 会认为这是同一个实例
    # TODO: 注意，${eureka.instance.instance-id}这个值不能相同，如果相同则注册中心会认为是同一个实例
    instance-id: abcmsc-provider-${server.port}
    # 设置当前Client向Server发送一次心跳的时间间隔，单位秒
    lease-renewal-interval-in-seconds: 1
    # 指定让Server认定当前Client已经失效的时间，将来可以从注册表中剔除了，单位秒
    lease-expiration-duration-in-seconds: 3


info:
  version: 1.0
  app:
    auth: Reythor
    name: abcmsc
  company:
    name: www.suyh.com
    addr: 广东深圳

management:
  # 开启所有监控终端
  endpoints:
    web:
      exposure:
        # 修改服务的状态为DOWN，使其不能通过注册中心访问该服务，而直接访问该服务地址还是可以的。
        # POST 请求 localhost:8081/actuator/service-registry
        # {"status": DOWN"}
        include: "*"
  # 开启shutdown监控终端
  # 服务下架，直接将服务停掉了。但是一般我们不这样做，而是仅修改状态即可
  endpoint:
    shutdown:
      enabled: true
