server:
  port: 9000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          # http://网关地址/服务名称（大写）/**
          # 允许小写的服务名称进行访问
          lowerCaseServiceId: true
  application:
    name: eureka-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

