server:
  port: 8100

spring:
  application:
    name: msc-eureka-server
eureka:
  instance:
    # 配置当前主机名
    # TODO: 注意 ${eureka.instance.hostname} 不能配置相同了，否则会认为是同一实例。客户端也只会到同一实例上注册一次
    # 就可能会出现，多个注册中心实例只有一个注册中心有客户端上来注册
    hostname: localhost-${server.port}
  client:
    # 单机eureka 时需要为false
    register-with-eureka: false  # 指定当前主机是否需要向Eureka Server注册自己
    fetch-registry: false   # 指定当前主机是否需要从Eureka Server下载服务注册表
    service-url:
      # 相同的配置项 eureka.client.service-url.defaultZone 在服务端是指定暴露给客户端访问的地址
      # 而它在客户端，则是访问eureka 服务的地址
      # 当前Eureka Server对外暴露的服务地址
      defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka,http://localhost:8300/eureka
  server:
    # 自我保护机制
    enable-self-preservation: true
    # 指定自我保护机制的开启阈值，默认为 0.85
    renewal-percent-threshold: 0.75
    # 设置 eureka server 端剔除不可用服务的时间窗，默认60秒，单位毫秒
    # 定时器的定时周期
    # 一直打印的日志：'AbstractInstanceRegistry  : Running the evict task with compensationTime'
    # eureka server 清理down 掉的微服务的定时任务时间窗，一次清理所有已经down 掉且满足踢掉的条件的微服务。
    eviction-interval-timer-in-ms: 5000
    # 推算期望每分钟心跳数的一个时间窗口时间段，默认为15 分钟。单位：毫秒
    renewal-threshold-update-interval-ms: 900000
