




spring:
  application:
    name: demo-suyh-provider


---
spring:
  config:
    activate:
      on-profile: local

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/suyh-eureka-server/eureka








