

---
spring:
  config:
    activate:
      on-profile: local

# 注册中心访问地址：http://localhost:8761/suyh-eureka-server/
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # 当前Eureka Server对外暴露的服务地址
      defaultZone: http://localhost:${server.port}/${server.servlet.context-path}/eureka
  server:
    # 自我保护机制
    enable-self-preservation: true
    # 指定自我保护机制的开启阈值，默认为 0.85
    renewal-percent-threshold: 0.85
    # 设置 eureka server 端剔除不可用服务的时间窗，默认60秒，单位毫秒
    # 定时器的定时周期
    # eureka server 清理down 掉的微服务的定时任务时间窗，一次清理所有已经down 掉且满足踢掉的条件的微服务。
    eviction-interval-timer-in-ms: 60_000
    # 推算期望每分钟心跳数的一个时间窗口时间段，默认为15 分钟。单位：毫秒
    renewal-threshold-update-interval-ms: 900_000

