server:
  port: 8381
spring:
  application:
    name: abcmsc-consumer-depart

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
      # defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka,http://localhost:8300/eureka
  instance:
    # 该ID 将会显示在eureka 注册中心的Status 那一栏
    # TODO: 注意，${eureka.instance.instance-id}这个值不能相同，如果相同则注册中心会认为是同一个实例
    instance-id: abcmsc-consumer-${server.port}
    # 设置当前Client向Server发送一次心跳的时间间隔，单位秒
    lease-renewal-interval-in-seconds: 1
    # 指定让Server认定当前Client已经失效的时间，将来可以从注册表中剔除了，单位秒
    lease-expiration-duration-in-seconds: 3

feign:
  client:
    config:
      default:
        connectTimeout: 5000   # 指定Feign客户端连接提供者的超时时限
        readTimeout: 5000      # 指定Feign客户端连接上提供者后，向提供者进行提交请求，从提交时刻开始，到接收到响应，这个时段的超时时限

# 修改负载均衡策略为：随机策略
#abcmsc-provider-depart:
#  ribbon:

#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule