server:
  port: 80

# 相同的服务这个应用的名字要相同，群集时以此名字来做相同服务的请求
spring:
  application:
    name: eureka-consumer

# 设置服务注册中心地址，指定注册中心集群的地址
eureka-center01: http://localhost:6001/eureka/
eureka-center02: http://localhost:6002/eureka/
# eureka.client.serviceUrl.defaultZone=http://user:123456@eureka01:8751/eureka/,http://user:123456@eureka02:8761/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-center01},${eureka-center02}

# 在Feign中需要开启 Hystrix
feign:
  hystrix:
    enabled: true